version: '3.5'

services:
  postgres:
    container_name: gobarber-db
    image: 'bitnami/postgresql:latest'
    restart: always
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}

  mongo:
    container_name: gobarber-notification
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - 27017:${MONGO_PORT}
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DATABASE}

  redis:
    container_name: gobarber-cache
    image: redis
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
